"""added personal collection

Revision ID: 43eabda1d630
Revises: 9cad4dfb5125
Create Date: 2018-03-28 13:55:03.557872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eabda1d630'
down_revision = '9cad4dfb5125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gifs', sa.Column('personal_collections', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Gifs', 'PersonalGifCollections', ['personal_collections'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Gifs', type_='foreignkey')
    op.drop_column('Gifs', 'personal_collections')
    # ### end Alembic commands ###
